Tab to 4 Spaces All project

diff --git a/grailsw b/grailsw
--- a/grailsw
+++ b/grailsw
@@ -20,15 +20,15 @@ die() {
 }
 
 earlyInit() {
-	return
+    return
 }
 lateInit() {
-	return
+    return
 }
 
 GROOVY_STARTUP=~/.groovy/startup
 if [ -r "$GROOVY_STARTUP" ]; then
-	. "$GROOVY_STARTUP"
+    . "$GROOVY_STARTUP"
 fi
 
 earlyInit
@@ -54,16 +54,16 @@ esac
 # Attempt to set JAVA_HOME if it's not already set
 if [ -z "$JAVA_HOME" ]; then
 
-	# Set JAVA_HOME for Darwin
-	if $darwin; then
+    # Set JAVA_HOME for Darwin
+    if $darwin; then
 
-		[ -z "$JAVA_HOME" -a -d "/Library/Java/Home" ] &&
-			export JAVA_HOME="/Library/Java/Home"
+        [ -z "$JAVA_HOME" -a -d "/Library/Java/Home" ] &&
+            export JAVA_HOME="/Library/Java/Home"
 
-		[ -z "$JAVA_HOME" -a -d "/System/Library/Frameworks/JavaVM.framework/Home" ] &&
-			export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"
+        [ -z "$JAVA_HOME" -a -d "/System/Library/Frameworks/JavaVM.framework/Home" ] &&
+            export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"
 
-	fi
+    fi
 
 fi
 
@@ -169,21 +169,21 @@ fi
 # Increase the maximum file descriptors if we can
 if [ "$cygwin" = "false" ]; then
     MAX_FD_LIMIT=`ulimit -H -n`
-	if [ "$MAX_FD_LIMIT" != "unlimited" ]; then
-	    if [ $? -eq 0 ]; then
-	        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-	            # use the businessSystem max
-	            MAX_FD="$MAX_FD_LIMIT"
-	        fi
+    if [ "$MAX_FD_LIMIT" != "unlimited" ]; then
+        if [ $? -eq 0 ]; then
+            if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+                # use the businessSystem max
+                MAX_FD="$MAX_FD_LIMIT"
+            fi
 
-	        ulimit -n $MAX_FD
-	        if [ $? -ne 0 ]; then
-	            warn "Could not set maximum file descriptor limit: $MAX_FD"
-	        fi
-	    else
-	        warn "Could not query businessSystem maximum file descriptor limit: $MAX_FD_LIMIT"
-	    fi
-	fi
+            ulimit -n $MAX_FD
+            if [ $? -ne 0 ]; then
+                warn "Could not set maximum file descriptor limit: $MAX_FD"
+            fi
+        else
+            warn "Could not query businessSystem maximum file descriptor limit: $MAX_FD_LIMIT"
+        fi
+    fi
 fi
 
 # Fix the cygwin agent issue
@@ -289,28 +289,28 @@ if $cygwin; then
     fi
     TOOLS_JAR=`cygpath --path --mixed "$TOOLS_JAR"`
     STARTER_CLASSPATH=`cygpath --path --mixed "$STARTER_CLASSPATH"`
-	# We build the pattern for arguments to be converted via cygpath
+    # We build the pattern for arguments to be converted via cygpath
     ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
     SEP=""
     for dir in $ROOTDIRSRAW; do
-    	ROOTDIRS="$ROOTDIRS$SEP$dir"
-	    SEP="|"
+        ROOTDIRS="$ROOTDIRS$SEP$dir"
+        SEP="|"
     done
     OURCYGPATTERN="(^($ROOTDIRS))"
     # Add a user-defined pattern to the cygpath arguments
     if [ "$GROOVY_CYGPATTERN" != "" ] ; then
-    	OURCYGPATTERN="$OURCYGPATTERN|($GROOVY_CYGPATTERN)"
+        OURCYGPATTERN="$OURCYGPATTERN|($GROOVY_CYGPATTERN)"
     fi
     # Now convert the arguments
-	ARGUMENTS=""
+    ARGUMENTS=""
     for arg in "$@" ; do
-    	CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
-    	if [ $CHECK -ne 0 ] ; then
-	    	convArg=`cygpath --path --ignore --mixed -- "$arg"`
-    	else
-			convArg=$arg
-    	fi
-		ARGUMENTS="$ARGUMENTS $convArg"
+        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
+        if [ $CHECK -ne 0 ] ; then
+            convArg=`cygpath --path --ignore --mixed -- "$arg"`
+        else
+            convArg=$arg
+        fi
+        ARGUMENTS="$ARGUMENTS $convArg"
     done
 fi
 
@@ -323,19 +323,19 @@ startGrails() {
   shift
   if [ -n "$GRAILS_OPTS" ]
      then
- 	GRAILS_OPTS="$GRAILS_OPTS"
+     GRAILS_OPTS="$GRAILS_OPTS"
      else
-	GRAILS_OPTS="-server -Xmx768M -Xms64M -Dfile.encoding=UTF-8"
-	if [ "$GRAILS_NO_PERMGEN" != "1" ]; then
-	   GRAILS_OPTS="$GRAILS_OPTS -XX:PermSize=32m -XX:MaxPermSize=256m"
-	fi
+    GRAILS_OPTS="-server -Xmx768M -Xms64M -Dfile.encoding=UTF-8"
+    if [ "$GRAILS_NO_PERMGEN" != "1" ]; then
+       GRAILS_OPTS="$GRAILS_OPTS -XX:PermSize=32m -XX:MaxPermSize=256m"
+    fi
   fi
   JAVA_OPTS="$GRAILS_OPTS $JAVA_OPTS $AGENT"
   # Start the Profiler or the JVM
   if $useprofiler; then
       runProfiler
   else
-  	if [ $# -eq 0 ] ; then         # no argument given
+      if [ $# -eq 0 ] ; then         # no argument given
          exec "$JAVACMD" $JAVA_OPTS \
           -classpath "$STARTER_CLASSPATH" \
           -Dgrails.home="$GRAILS_HOME" \
@@ -345,7 +345,7 @@ startGrails() {
           --main $CLASS \
           --conf "$STARTER_CONF" \
           --classpath "$CP"
-  	else
+      else
          exec "$JAVACMD" $JAVA_OPTS \
           -classpath "$STARTER_CLASSPATH" \
           -Dgrails.home="$GRAILS_HOME" \
@@ -356,7 +356,7 @@ startGrails() {
           --conf "$STARTER_CONF" \
           --classpath "$CP" \
           "${ARGUMENTS}"
-  	fi
+      fi
   fi
 }
 
